drop table if exists member CASCADE;
create table member
(
    id bigint generated by default as identity,
    name varchar(255) not null,
    password varchar(255) not null,
    reg_date timestamp not null,
    mod_date timestamp not null,
    primary key (id)
);